% --- INICIO DE PLANTILLA PERSONALIZADA ---
\documentclass[oneside,11pt]{Latex/Classes/PhDthesisPSnPDF}

% --- Paquetes Originales ---
\usepackage{blindtext}
\usepackage{actuarialangle} 
\usepackage{tabularx}
\usepackage{float}
\usepackage{multirow, array}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage{longtable}
\usepackage{latexsym,amsmath,amssymb,amsfonts}
\usepackage{enumitem}
\usepackage{xparse}
\usepackage{booktabs}
\usepackage[round, sort, numbers]{natbib}  
\usepackage{adjustbox}
\usepackage[utf8]{inputenc}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{cleveref}

% Definición de colores
\definecolor{miblue}{RGB}{68, 114, 196}

% --- CAMBIO CRÍTICO 1: Usar \input para macros en el preámbulo ---
% \include da problemas antes del begin document. \input es seguro.
\input{Latex/Macros/MacroFile1}

% --- Definiciones de seguridad (por si la clase falla al cargar alguna variable) ---
\providecommand{\facultad}[1]{\def\lafacultad{#1}}
\providecommand{\escudofacultad}[1]{\def\elescudo{#1}}
\providecommand{\degree}[1]{\def\elgrado{#1}}
\providecommand{\director}[1]{\def\eldirector{#1}}
\providecommand{\lugar}[1]{\def\ellugar{#1}}
\providecommand{\degreedate}[1]{\def\lafecha{#1}}

% --- Configuración para bloques de código de R (Pandoc) ---

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                         DATOS (Conectados a RMarkdown)                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{Analisis de Precios de Carros en el mercado de segunda mano}
\author{Carlos Herrera \\ Juan Hernandez}

% Lógica para Facultad: Si la defines en el YAML la usa, si no, usa la default

\facultad{Facultad de Ciencias Económicas y Sociales \\ Escuela de
Estadistica y Ciencias Actuariales}
  \escudofacultad{Latex/Classes/Escudos/faces}

\degree{Computación I}
\director{Prof.~Jesus Ochoa \\ Prof.~Oliver Triveño}
\degreedate{Abril 2026} 
\lugar{Caracas}

\portadatrue 

% Metadatos PDF
\keywords{}
\subject{}

% --- CORRECCIÓN PARA PANDOC NUEVO (Imágenes) ---
\makeatletter
\providecommand{\pandocbounded}[1]{#1}
\makeatother


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   DOCUMENTO                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

\maketitle

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  PRÓLOGO                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frontmatter

% Puedes agregar dedicatorias desde el YAML si quieres, o dejarlas fijas aquí

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   ÍNDICES                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}

\tableofcontents



\cleardoublepage

  \cleardoublepage       % Empieza en página derecha (estándar en tesis)
  \chapter*{Resumen}     % Crea el título "Resumen" sin numeración (Capítulo *)
  \addcontentsline{toc}{chapter}{Resumen} % (Opcional) Lo añade al índice
  
  En el presente informe se realiza un análisis exploratorio de los
datos de precios para el año 2023 de una selección de carros. Partiendo
de variables como marca, modelo, año, tipo de transmisión, millaje,
entre otras; se examinan cuales los factores que afectan su precio,
aplicando técnicas estadísticas descriptivas y visualización de datos
con R.             % Aquí se pega el texto que escribiste en el YAML
  
  \cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   CONTENIDO (El Corazón)          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\mainmatter
\def\baselinestretch{1.5}

% --- CAMBIO CRÍTICO 2: Aquí RMarkdown inyecta todo tu texto ---
\chapter*{Introducción}

A lo largo de la vida de una persona, pocas decisiones económicas son
tan importantes como la compra de una casa o un carro. El en el caso de
un carro, el mercado automotriz es altamente dinámico y se caracteriza
por la interacción de múltiples variables a la hora de determinar el
valor de un vehículo. A diferencia de otros bienes, como un inmueble, un
carro es un activo que suele sufrir de una rápida depreciación; cuyo
valor, además de verse afectado por el uso, también podria verse
afectado por factores como avances tecnológicos, prestigio de la marca,
modelo especifico, entre otros. \newline \newline Hoy en día, factores
como el sistema de propulsión; ya sean los tradicionales, como gasolina
o diésel, hasta las nuevas tecnologías hibridas y eléctricas, agregan
nuevas dimensiones a la hora de determinar el valor de un carro.
Entender como estas características técnicas, junto con el uso y la
antigüedad del carro afectan su precio se vuelve entonces de suma
importancia para aquellos consumidores o empresas que quieran maximizar
u optimizar su inversión. \newline \newline Es por ello que en el
presente trabajo se busca aplicar la estadística descriptiva para
explorar y caracterizar el mercado de vehículos, tratando de identificar
patrones que nos permitan tener una visión más clara y objetiva sobre
cuáles son los factores que afectan el valor de un carro

\section*{Estructura del Informe}

Este documento técnico se encuentra estructurado en cinco capítulos
fundamentales:

\begin{itemize}
    
    \item En el \textbf{Capítulo I}, se plantea la problemática de la volatilidad de precios en el mercado automotriz de segunda mano y el impacto de la depreciación técnica, formulando las preguntas de investigación y delimitando el alcance del estudio basado en las marcas y modelos analizados.
    
    \item El \textbf{Capítulo II} establece el Marco Teórico, definiendo los conceptos de estadística descriptiva fundamentales como las medidas de tendencia central, los cuartiles para la detección de valores atípicos y la correlación de Pearson, necesarios para interpretar la relación entre el kilometraje y el valor de mercado.

    \item El \textbf{Capítulo III} describe el Marco Metodológico, detallando el proceso de limpieza y preparación de datos (ETL) realizado en R, el tratamiento de valores ausentes (especialmente en vehículos eléctricos) y los criterios de segmentación por tipo de combustible y transmisión.

    \item El \textbf{Capítulo IV} presenta el Análisis de Resultados, donde se exhiben las tablas de frecuencia y los gráficos (histogramas y diagramas de caja) generados dinámicamente, discutiendo los hallazgos sobre la distribución de precios por marca y la eficiencia de los motores según su tamaño.

    \item Finalmente, en el \textbf{Capítulo V}, se exponen las Conclusiones y Recomendaciones estratégicas derivadas del análisis cuantitativo, orientadas a la valoración precisa de activos y a la optimización de decisiones de compra y venta basadas en evidencia estadística.
\end{itemize}

Este reporte no solo pretende ofrecer una radiografía del estado actual
del mercado de vehículos usados, sino también establecer una metodología
reproducible para el análisis de activos físicos sujetos a depreciación
temporal y tecnológica.

\chapter{Planteamiento del Problema}

En el mercado automotriz actual, el valor de un vehículo no es una cifra
estática, sino el resultado de una interacción multivariable donde
convergen la obsolescencia tecnológica, el desgaste físico y las
preferencias del consumidor. Para un analista o un comprador, la
imprevisibilidad de los precios de reventa representa un riesgo
financiero significativo. \newline \newline El conjunto de datos bajo
estudio presenta una muestra heterogénea que incluye desde vehículos de
combustión tradicional hasta modelos eléctricos de alta gama. Esta
diversidad genera una alta dispersión en los precios, dificultando la
identificación de un ``valor justo''. El problema radica en la falta de
una caracterización estadística clara que permita entender cómo factores
como el kilometraje acumulado, el año de fabricación y el tipo de
combustible (especialmente ante el auge de los motores híbridos y
eléctricos) impactan directamente en la valoración del activo. \newline
\newline Sin un análisis descriptivo robusto, las decisiones de compra y
venta se basan en percepciones subjetivas y no en el comportamiento real
de los datos, lo que justifica la necesidad de este estudio.

Para orientar el análisis, se plantean las siguientes interrogantes:

\textbf{1.} ¿Cuál es el perfil de distribución de los precios de los
vehículos y qué tan alta es su variabilidad interna?

\textbf{2.} ¿Existe una relación inversamente proporcional clara entre
el kilometraje y el precio en todas las marcas por igual?

\textbf{3.} ¿Cómo se comportan los precios de los vehículos según su
tipo de energía (Gasolina vs.~Eléctrico/Híbrido), o tipo de transmision?

\section{Justificación}

La presente investigación se justifica desde tres dimensiones
fundamentales: la económica, la técnica y la académica. \newline
\newline Desde la dimensión económica, la adquisición de un vehículo
representa una de las inversiones más significativas para el patrimonio
personal o empresarial. No obstante, el mercado de automóviles de
segunda mano se caracteriza por una alta asimetría de información, donde
el precio suele estar sujeto a la especulación o a una valoración
empírica del estado del bien. Este estudio proporciona una base objetiva
que permite comprender el comportamiento de los precios, facilitando una
toma de decisiones informada que minimice el riesgo financiero. \newline
\newline Desde la dimensión técnica, la industria automotriz atraviesa
una transición energética sin precedentes. La coexistencia de motores de
combustión interna con tecnologías híbridas y eléctricas plantea un reto
para los métodos de valoración tradicionales. La aplicación de
herramientas de \textbf{Estadística Descriptiva} en este contexto
permite caracterizar estas nuevas categorías y determinar si su
comportamiento de mercado sigue los patrones históricos o si, por el
contrario, requieren de marcos de análisis diferenciados debido a su
naturaleza tecnológica. \newline \newline Desde la dimensión académica,
este trabajo se inserta en la formación de la Escuela de Estadística y
Ciencias Actuariales, demostrando la capacidad del lenguaje de
programación R para el manejo de grandes volúmenes de datos y la
generación de reportes dinámicos. La relevancia del estudio reside en la
transformación de datos crudos en indicadores estadísticos (medidas de
posición, dispersión y forma), validando que el análisis exploratorio de
datos (EDA) es una etapa indispensable para garantizar la robustez de
cualquier inferencia o modelo predictivo posterior.

\section{Objetivos}

\subsection{Objetivo General}

Analizar estadísticamente el comportamiento de los precios de los
vehículos basándose en sus características técnicas y de uso, mediante
la aplicación de herramientas de estadística descriptiva y visualización
de datos en el lenguaje R.

\subsection{Objetivos Específicos}

\begin{enumerate}
  \item Caracterizar las variables cualitativas (Marca, Combustible, Transmisión) a través de tablas de frecuencias y sus graficos asociados.
  \item Determinar las medidas de tendencia central y dispersión para las variables cuantitativas (Precio, Kilometraje, Año).
  \item Cuantificar las correlaciones entre las distintas variables numericas.
  \item Identificar la presencia de valores atípicos (outliers) en los precios que puedan sesgar el análisis del mercado.
  \item Comparar la estructura de costos entre vehículos de combustión interna y tecnologías alternativas.
\end{enumerate}

\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las características de cada vehículo
registrado en la base de datos. Se consideran las dimensiones técnicas
del producto (marca, modelo, tipo de motor y transmisión) y las métricas
de valor y uso (precio de mercado, kilometraje y año de fabricación) que
definen su perfil comercial.

\subsection{Vertical}

La cobertura vertical del trabajo de investigación comprende un total de
2.500 observaciones (registros). Cada fila representa un vehículo único
disponible en el mercado de segunda mano. El alcance temporal de los
datos es longitudinal, abarcando modelos desde el año 2000 hasta el año
2024, lo que permite un análisis de la depreciación y evolución
tecnológica a corto y mediano plazo.

\begin{table}[ht]
\centering
\caption{Variables consideradas en el estudio} 
\resizebox{15cm}{!} {
\begin{tabular}{cll}
  \hline
  \textbf{TIPO} & \textbf{VARIABLE} & \textbf{DESCRIPCIÓN} \\ 
  \hline
  Categórica & Brand & Nombre del fabricante del carro \\ 
  Numérica & Year & Año en que fue fabricado el carro \\ 
  Numérica & Engine.Size & Cilindrad del motor del carro en litros  \\ 
  Categórica & Fuel.Type & Tipo de combustible o sistema de propulsion (e.g. Gasolina, Electrico) \\ 
  Categórica & Transmission & Tipo de transmision del carro (Manual, Automatica) \\ 
  Numérica & Mileage & Millas recorridas en el carro \\ 
  Categórica & Condition & Condicion del carro segun su uso (e.g. Nuevo, Usado) \\ 
  Numérica & Price & Precio de venta en dolares \\ 
  Categórica & Model & Nombre del modelo especifico del carro \\ 
   \hline
\end{tabular}
}
\end{table}

\section{Periodo de Referencia}

Los registros de precios de los carros presentes en la base de datos
usados son los precios de dicho carro al momento de realizar la
recolección de los datos, por lo que los precios son para el ano 2023.
Sin embargo, cabe acotar que los anos de producción de los carros
presentes en la lista van desde el 2000 al 2023. La base de datos
analizada actúa como una fotografía del mercado secundario actual,
reflejando cómo se valoran hoy los activos producidos en las últimas dos
décadas.

\begin{itemize}
  \item Permite capturar el ciclo de vida completo de un vehículo, desde su salida de concesionario hasta su etapa de obsolescencia.
  \item Facilita el estudio de la transición tecnológica, integrando modelos de combustión de principios de siglo con las innovaciones eléctricas e híbridas comercializadas en el último bienio. \end{itemize}

\section{Variables}

La variable principal en estudio (Variable Dependiente/Objetivo) es
Price, que representa el valor de mercado del vehículo medido en
unidades monetarias. Como variables explicativas o independientes se
analizan:

\begin{enumerate}
  \item Variables de Uso y Desgaste: \textbf{Year} y \textbf{Mileage}
  \item Variables Categóricas: \textbf{Brand}, \textbf{Model} y \textbf{Condition}
  \item Variables de Especificación Técnica: \textbf{Engine.Size}, \textbf{Fuel.Type} y \textbf{Transmission}
\end{enumerate}

\chapter{Marco Teórico}

\section{Bases Teóricas}

El presente capítulo establece los fundamentos teóricos y estadísticos
necesarios para interpretar la dinámica de precios y el desgaste de los
vehículos objeto de estudio. Se abordan conceptos de estadística
descriptiva y métricas financieras aplicadas a activos físicos. De igual
forma se explican los conceptos tecnicos automotrices necesarios para
entender a mayor detalle el estudio a realizar.

\subsection{Fundamentos Estadísticos}

\subsubsection{Análisis Exploratorio de Datos (EDA)}

El Análisis Exploratorio de Datos (EDA, por sus siglas en inglés) es la
etapa fundamental de todo proyecto de ciencia de datos. Su objetivo
primordial es analizar los conjuntos de datos para determinar patrones,
detectar anomalías (valores atípicos), verificar suposiciones y resumir
características principales, generalmente mediante métodos de
visualización, antes de aplicar modelos complejos o extraer conclusiones
definitivas.

\subsubsection {Medidas de Tendencia Central}

Son parámetros que informan sobre el centro de la distribución de una
muestra:

\begin{itemize}
  \item Media Aritmética ($\bar{x}$): Es el promedio de los datos. En este estudio, representa el precio de equilibrio, aunque es sensible a valores extremos (como modelos de lujo).
  
  $$\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i$$

  \item Mediana ($\tilde{x}$): Es el valor que divide la muestra en dos partes iguales (50 por ciento). Es la medida de posición más robusta para analizar precios, ya que no se ve afectada por los outliers.
  
  \item Moda: Es el valor que aparece con mayor frecuencia. Útil para identificar las marcas o modelos de vehículos más comunes en la muestra.

\end{itemize}

\subsubsection {Asimetría de Fisher (coeficiente de asimetría)}

Es una medida estadística que indica el grado de falta de simetría de
una distribución de probabilidad con respecto a su media.Se define
matemáticamente como el tercer momento estandarizado:

\[\gamma_1 = \frac{E[(X - \mu)^3]}{\sigma^3}\]

Interpretación de los Resultados

\begin{itemize}
  \item $\gamma_1 = 0$: La distribución es simétrica. Los datos se reparten de forma uniforme a ambos lados de la media (la media, la mediana y la moda suelen coincidir).
  \item $\gamma_1 > 0$: Asimetría positiva (a la derecha). La "cola" de la distribución es más larga hacia los valores altos; existe una mayor concentración de datos en los valores bajos.
  \item$\gamma_1 < 0$: Asimetría negativa (a la izquierda). La "cola" es más larga hacia los valores bajos; la mayor concentración de datos está en los valores altos.
\end{itemize}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-1-1} \end{center}

\subsubsection {Medidas de Dispersión}

Permiten cuantificar qué tan alejados están los datos respecto al
promedio:

\begin{itemize}
  \item Desviación Estándar ($\sigma$): Indica el grado de variabilidad de los precios en relación con la media.

$$s = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n}}$$

  \item Rango Intercuartílico (RIC): Diferencia entre el tercer y primer cuartil ($Q_3 - Q_1$). Representa el 50 por ciento central de la muestra y es la base para la construcción de los Diagramas de Caja.
\end{itemize}

\subsubsection {Estudio de correlacion lineal}

\textbf{Covarianza (\(s_{xy}\) / \(\sigma_{xy}\))} \newline \newline La
Covarianza es una medida estadística que indica el grado de variación
conjunta de dos variables aleatorias respecto a sus medias. Es el
indicador básico de la dependencia lineal entre dos variables; permite
entender si, cuando una variable aumenta, la otra tiende a aumentar o
disminuir. \newline

\begin{itemize}
\item Covarianza Positiva ($s_{xy} > 0$): Indica una relación directa. Ambas variables tienden a variar en el mismo sentido (si $X$ sube, $Y$ sube).
\item Covarianza Negativa ($s_{xy} < 0$): Indica una relación inversa. Cuando una variable aumenta, la otra tiende a disminuir.
\item Covarianza Nula ($s_{xy} \approx 0$): Indica que no existe una relación lineal aparente entre las dos variables.
\end{itemize}

\textbf{Coeficiente de correlación de Pearson (\(r\))} \newline \newline
Es una medida estadística que cuantifica la fuerza y la dirección de la
relación lineal entre dos variables cuantitativas.Sus posibles valores
se encuentran entre -1 y +1. Mientras mas alejado del cero, mayor sera
la fuerza de la correlacion entre las dos variables. Al igual que la
covarianza, un resultado negativo indica una relacion inversa y un
resultado positivo indica una relacion directa entre ambas variables.

\[r = \frac{S_{xy}}{S_x \cdot S_y}\]

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-2-1} \end{center}

\subsection {Fundamentos economicos}
\subsubsection{Depreciación de Activos Móviles}

Desde una perspectiva económica, la depreciación es la pérdida de valor
de un bien debido al uso, el paso del tiempo o la obsolescencia. En el
mercado automotriz, este fenómeno se analiza mediante la relación entre
la antigüedad (Year) y el uso acumulado (Mileage) con el precio (Price)
del vehiculo.

\subsection {Fundamentos tecnicos automotrices}
\subsubsection {Sistemas de Propulsión (Fuel Type)}

La naturaleza del motor determina no solo el rendimiento, sino también
la estructura de costos y la velocidad de depreciación del vehículo:

\begin{itemize}
\item Motores de Combustión Interna (ICE): Utilizan derivados del petróleo (Gasolina o Diesel). Su valor de mercado está fuertemente ligado a la cilindrada (Engine Size); generalmente, a mayor tamaño de motor, mayor es el consumo y el costo de mantenimiento.
\item Vehículos Eléctricos (EV): Operan mediante baterías y motores eléctricos. Se caracterizan por la ausencia de cilindrada tradicional (registrados como NA en la base de datos). Su precio de mercado suele ser superior debido al costo de la tecnología de baterías, aunque su depreciación puede ser distinta a la de los carros convencionales.
\item Vehículos Híbridos (HEV): Combinan un motor de combustión con uno eléctrico. Representan un punto medio en la escala de precios y eficiencia, buscando optimizar el consumo de combustible en entornos urbanos.
\end{itemize}

\subsubsection {Sistemas de Transmisión}

La transmisión es el mecanismo que administra la potencia del motor
hacia las ruedas. En el mercado secundario, esta variable es un factor
determinante en la preferencia del consumidor:

\begin{itemize}
\item Transmisión Manual: Requiere la intervención directa del conductor para el cambio de marchas. Históricamente asociada a un menor costo de adquisición y mantenimiento, además de una mayor eficiencia de combustible en modelos antiguos.

\item Transmisión Automática: El sistema gestiona los cambios de forma autónoma. Aunque suele incrementar el precio inicial del vehículo, es la tecnología predominante en modelos recientes y de alta gama (como BMW o Tesla), influyendo positivamente en el valor de reventa en mercados modernos.
\end{itemize}

\chapter{Marco Metódico}

En esta sección se presentan las metodologías, procedimientos
algorítmicos y técnicas de curaduría de datos implementadas para
transformar la muestra inicial en un conjunto de datos técnicamente
verosímil. Se detalla el tratamiento de la fuente de datos
precios\_carros.csv, los protocolos de limpieza (Data Wrangling) y el
procedimiento de imputación mediante fuentes externas utilizado para
corregir las inconsistencias detectadas en las variables de precio y
millaje. \newline \newline Igualmente se explican las tecnicas
estadisticas para posterior análisis utilizando el lenguaje de
programación R (versión 4.x) bajo el entorno de desarrollo RStudio,
empleando el paradigma ``Tidyverse'' para la manipulación y
transformación de estructuras de datos, así como funciones de
aleatorización controlada para el ajuste de la muestra.

\section{Bases metódicas utilizadas en el trabajo de investigación}

El diseño de la investigación es de carácter cuantitativo, no
experimental y de corte transversal con perspectiva histórica, dado que
se analizan datos observados en un punto del tiempo, pero que abarcan
modelos de distintos años de fabricación. A continuación, se describen
las etapas fundamentales del procesamiento:

\subsection{Procesamiento y Limpieza de Datos (ETL)}

La calidad de las conclusiones estadísticas depende directamente de la
pureza de la base de datos original. Tras una inspección inicial del
archivo precios\_carros.csv mediante el lenguaje R, se identificaron
anomalías estructurales y lógicas que requirieron una intervención
inmediata bajo los siguientes criterios: \newline \newline
\textbf{Depuración de Registros Incompletos}

En primera instancia, se procedió a la eliminación de 250 registros que
presentaban valores nulos (NA) en todos sus campos. Esta decisión se
tomó para evitar sesgos en el cálculo de los momentos estadísticos
(media, varianza) que podrían derivar en interpretaciones incorrectas de
los datos. \newline \newline \textbf{Tratamiento de Discrepancias
Lógicas y Técnicas}

Posteriormente, se realizó una auditoría de coherencia entre los
registros y las especificaciones técnicas reales de la industria
automotriz, aplicando los siguientes filtros de corrección:

\begin{itemize}

 \item Anacronismos de Comercialización: Se eliminaron o corrigieron registros donde el año de fabricación era previo al lanzamiento oficial del modelo (ej. modelos de Tesla registrados antes de 2015).

 \item Consistencia en el Sistema de Propulsion: Se detectaron errores de clasificación en el tipo de combustible. Se ajustaron aquellos vehículos listados como Eléctricos que poseían cilindrada (Engine Size) y viceversa, garantizando que los modelos eléctricos tuvieran un valor de NA en el tamaño del motor.

 \item Validación de Cilindrada: Se filtraron registros con tamaños de motor fuera de los rangos mecánicos posibles para el modelo específico (ej. motores de 8 litros en sedanes compactos), ajustándolos a los estándares del fabricante para mantener la representatividad de la muestra.
 \end{itemize}

\textbf{Reingeniería de Datos y Validación Externa}

Tras identificar que la base de datos original presentaba una
distribución de precios y kilometrajes excesivamente uniforme e
incoherente con el año de fabricación (ausencia de correlación entre
antigüedad y valor), se procedió a una fase de curaduría de datos para
aproximar la muestra a la realidad del mercado automotriz.

El proceso de ajuste se ejecutó bajo la siguiente metodología:

\begin{itemize}

 \item Recolección de Parámetros Reales: Se utilizó el portal especializado CarGurus como fuente de referencia externa para extraer métricas actualizadas de precios y millas recorridas según marca y modelo.

 \item Estratificación Temporal: Se segmentó la muestra en cohortes quinquenales (2000-2005, 2006-2010, 2011-2015, 2016-2020 y 2021-2023). Esta técnica de estratificación permitió capturar el comportamiento del valor del carro y su millaje en distintas etapas de su ciclo de vida.

 \item Muestreo de Referencia: Para cada estrato y modelo, se recolectó una submuestra representativa de aproximadamente 30 observaciones, estableciendo así los límites técnicos del mercado.

 \item Imputación Aleatoria Controlada: Utilizando el lenguaje de programación R, se reemplazaron los valores ilógicos originales mediante la generación de números aleatorios. Para garantizar la representatividad y evitar el ruido de los valores extremos, se restringió el rango de asignación al 75% central de los datos de millas y precios recopilados en la fase de investigación externa.
\end{itemize}

\subsection {Técnicas de Análisis Estadístico}

\begin{itemize}
 \item Análisis Univariado: Se utilizarán medidas de tendencia central (Media, Mediana) y de dispersión (Desviación Estándar, Coeficiente de Variación) para caracterizar el comportamiento individual del Precio, el Kilometraje y el Año. Se emplearán histogramas de frecuencias para observar la forma de la distribución (Simetría y Curtosis).

 \item Análisis Bivariado y Comparativo: Para cumplir con el objetivo de comparar marcas y tipos de combustible, se aplicará la técnica de Segmentación de Datos. Se utilizarán Diagramas de Caja (Boxplots), los cuales permiten visualizar la mediana, los cuartiles y, fundamentalmente, identificar la existencia de valores atípicos (outliers) en los precios de cada categoría.

 \item Análisis de Relación: Para evaluar la relación entre el uso (Kilometraje) y el valor (Precio), se emplearán Diagramas de Dispersión (Scatter Plots) y el cálculo del Coeficiente de Correlación de Pearson, determinando así la intensidad y dirección de la asociación entre ambas variables.
\end{itemize}

\chapter{Analisis de Resultados}

El presente capítulo constituye el núcleo del estudio, donde se exponen
y examinan de manera detallada los hallazgos obtenidos tras el
procesamiento de la base de datos de 1,866 vehículos. El objetivo
principal es transformar los datos crudos en información estadística de
valor que permita caracterizar el comportamiento del mercado automotriz
de segunda mano para el año 2023. Aunque no es una variable de estudio,
dentro de los modelos representados en la muestra, hay una
representacion de sedans compactos y grandes, asi como SUV de mediano y
gran tamaño. Cada marca de la muestra tiene 4 modelos diferentes y una
combinacion semejante de carros por tipo de carroceria.

\section {Estudio de Precios por Marca}

Las marcas representadas en la muestra pueden ser divididas en 3 grupos.
Un primer grupo conformado por Ford, Honda y Toyota, las cuales son
consideradas marcas de consumo masivo, mientras que el grupo de marcas
Audi, BMW y Mercedes Benz serian consideradas marcas de lujo. Por
ultimo, se tiene el caso particular de Tesla, que tambien se
consideraria una marca de lujo, pero tiene la peculiaridad de ser una
marca relativamente nueva que fabrica exclusivamente vehiculos
electricos.

\subsection {Resumen Estadistico de Precios por Marca}
\begin{table}[!h]
\centering
\caption{\label{tab:unnamed-chunk-3}Resumen Estadístico de Precios por Marca}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lccc>{}c}
\toprule
\textcolor{black}{\textbf{Marca}} & \textcolor{black}{\textbf{Total de carros}} & \textcolor{black}{\textbf{Precio promedio}} & \textcolor{black}{\textbf{Desviacion estandar}} & \textcolor{black}{\textbf{Coeficiente de Variacion}}\\
\midrule
\cellcolor{gray!10}{Audi} & \cellcolor{gray!10}{273} & \cellcolor{gray!10}{21,091.78} & \cellcolor{gray!10}{14,915.68} & \em{\cellcolor{gray!10}{70.72}}\\
BMW & 315 & 22,055.13 & 14,253.49 & \em{64.63}\\
\cellcolor{gray!10}{Ford} & \cellcolor{gray!10}{307} & \cellcolor{gray!10}{11,519.09} & \cellcolor{gray!10}{8,196.44} & \em{\cellcolor{gray!10}{71.16}}\\
Honda & 303 & 12,672.63 & 6,895.22 & \em{54.41}\\
\cellcolor{gray!10}{Mercedes} & \cellcolor{gray!10}{240} & \cellcolor{gray!10}{27,999.02} & \cellcolor{gray!10}{16,692.46} & \em{\cellcolor{gray!10}{59.62}}\\
\addlinespace
Tesla & 82 & 51,690.84 & 15,965.53 & \em{30.89}\\
\cellcolor{gray!10}{Toyota} & \cellcolor{gray!10}{346} & \cellcolor{gray!10}{13,978.80} & \cellcolor{gray!10}{8,111.27} & \em{\cellcolor{gray!10}{58.03}}\\
\cellcolor{lightgray}{\textbf{Total Muestra}} & \cellcolor{lightgray}{\textbf{1,866}} & \cellcolor{lightgray}{\textbf{19,226.51}} & \cellcolor{lightgray}{\textbf{14,976.39}} & \em{\cellcolor{lightgray}{\textbf{77.89}}}\\
\bottomrule
\end{tabular}}
\end{table}

En la tabla 4.1, se observan los precios promedios por marca y es
notable la diferencia entre la media de precios de cada uno de los
grupos mencionados anteriormente. Las marcas de consumo masivo tienen un
precio promedio considerablemente menor a las de lujo. En el caso de
Tesla es aun mas notorio su alto precio promedio, principalmente debido
a que los modelos de dicha marca salen al mercado a partir del año 2015,
y su promedio no se ve arrastrado hacia abajo por precios de carros de
mayor antiguedad, y por lo tanto su variabilidad tambien es la mas baja
de entre todas las marcas. \newline \newline La marca con el precio
promedio mas bajo es Ford, pero tambien es la que tiene mayor
variabilidad en sus precios. Haciendo a un lado los carros de la marca
Tesla, la marca con mayor precio promedio es Mercedes Benz. \newline
\newline En general, se observa una alta variabilidad en los precios de
los carros en la muestra.

\subsection {Distribucion Global de Precios}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-4-1} \end{center}

En el siguiente histograma observamos que existe una alta asimetria
hacia la derecha, esto indica que la mayor concentración de vehículos se
encuentra en los rangos de precios bajos y medios, mientras que la
``cola'' de la distribución se extiende hacia valores altos,
representados por modelos de lujo o tecnologías más costosas como Tesla.
Lo que quiere decir que los precios de los carros se concentran
mayoritariamente en un rango entre 5 mil y 15 mil dolares y siendo muy
pocos los que exceden un precio de 50 mil dolares. \newline \newline El
mercado se caracteriza por una amplia oferta de vehículos económicos,
pero con una dispersión significativa impulsada por un pequeño segmento
de vehículos de alta gama que estira la distribución hacia la derecha.

\subsection {Dispersion de Precios por Marca}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-5-1} \end{center}

Se observa una clara segmentación entre marcas de lujo y marcas de
consumo masivo. Tesla destaca con la mediana de precio más alta (cercana
a los \$50,000), seguida por Mercedes, BMW y Audi. En contraste, Ford,
Honda y Toyota presentan costos mucho más bajos y compactos. \newline
\newline El gráfico confirma la presencia de numerosos valores atípicos
representados por puntos por encima de los bigotes superiores. Audi y
BMW presentan outliers significativos que superan los \$75,000,
probablemente representando a los modelos mas nuevos de SUV de las
marcas.

\subsection {Precios Promedios por año de Fabricacion del carro}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-6-1} \end{center}

En la grafica de linea de tiempo se observa que los precios de los
carros cuyo año de produccion es menor a 2010 mantienen un precio
cercano a los 10 mil dolares, independientemente de la marca. Pero a
partir de este punto, ocurre un aumento de los precios, siendo mas suave
en las marcas de consumo masivo pero mas notorio en las marcas de lujo,
que a partir de este punto aumentan de precio considerablemente. En el
caso de los carros de la marca Tesla, podemos ver que sus precios se
comportan de una manera diferente. Esto se debe a la introduccion de
modelos de gamas mas economicas a partir del año 2020, lo que hace que
su precio promedio baje en ese punto, en vez de subir. Sin embargo, se
observa que a partir del año 2020 el comportamiento de sus precios esta
mas acorde al del resto del mercado, donde el precio promedio de sus
carros es cada vez mas alto a medida que el año de fabricacion se va
acercando al 2023.

\section {Estudio de Millajes por Marca}

\subsection {Resumen Estadistico de Millaje por Marcas}

\begin{table}[!h]
\centering
\caption{\label{tab:unnamed-chunk-7}Resumen Estadístico de Millaje por Marca}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lccc>{}c}
\toprule
\textcolor{black}{\textbf{Marca}} & \textcolor{black}{\textbf{Total de carros}} & \textcolor{black}{\textbf{Millaje promedio}} & \textcolor{black}{\textbf{Desviacion estandar}} & \textcolor{black}{\textbf{Coeficiente de Variacion}}\\
\midrule
\cellcolor{gray!10}{Audi} & \cellcolor{gray!10}{273} & \cellcolor{gray!10}{78,117.04} & \cellcolor{gray!10}{43,052.92} & \em{\cellcolor{gray!10}{55.11}}\\
BMW & 315 & 86,093.36 & 47,990.51 & \em{55.74}\\
\cellcolor{gray!10}{Ford} & \cellcolor{gray!10}{307} & \cellcolor{gray!10}{90,512.53} & \cellcolor{gray!10}{45,444.75} & \em{\cellcolor{gray!10}{50.21}}\\
Honda & 303 & 84,529.78 & 48,801.04 & \em{57.73}\\
\cellcolor{gray!10}{Mercedes} & \cellcolor{gray!10}{240} & \cellcolor{gray!10}{69,675.23} & \cellcolor{gray!10}{47,357.88} & \em{\cellcolor{gray!10}{67.97}}\\
\addlinespace
Tesla & 82 & 30,862.63 & 15,594.34 & \em{50.53}\\
\cellcolor{gray!10}{Toyota} & \cellcolor{gray!10}{346} & \cellcolor{gray!10}{82,637.46} & \cellcolor{gray!10}{46,962.79} & \em{\cellcolor{gray!10}{56.83}}\\
\cellcolor{lightgray}{\textbf{Total Muestra}} & \cellcolor{lightgray}{\textbf{1,866}} & \cellcolor{lightgray}{\textbf{80,220.03}} & \cellcolor{lightgray}{\textbf{47,307.31}} & \em{\cellcolor{lightgray}{\textbf{58.97}}}\\
\bottomrule
\end{tabular}}
\end{table}

A diferencia de los precios por marca, los millajes no parecen verse
influenciados por el grupo al que pertenezca la marca, pues no hay
grandes diferencias en los millajes entre el grupo de marcas de consumo
masivo y el grupo de marcas de lujo. \newline \newline Aunque existe una
ligera diferencia, teniendo las marcas como Ford, Honda y Toyota un
mayor millaje promedio, no es esta diferencia tan notable como en los
precios promedios. En el caso de Tesla ocurre lo mismo que con los
precios, pues sus valores de millaje se ven afectados por ser una marca
relativamente nueva. \newline \newline Ford lidera el millaje promedio
con 90,512.53 millas, lo que sugiere que los propietarios de esta marca
tienden a conservar y utilizar sus vehículos por trayectos más largos
antes de ponerlos a la venta en el mercado secundario; mientras que la
marca Mercedes Benz registra el Coeficiente de variacion mas más alto.
Esto refleja una muestra muy heterogénea donde coexisten vehículos
Mercedes con muy poco uso junto a otros con un millaje extremadamente
alto, lo que dificulta analisar los valores para la marca sin considerar
otras variables.

\subsection {Distribucion Global de Millajes}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-8-1} \end{center}

La muestra abarca un espectro muy amplio que va desde vehículos casi
nuevos o nuevos, hasta unidades con un desgaste extremo que superan las
175,000 millas. \newline \newline A diferencia de la variable precio, el
millaje muestra una distribución un poco más equilibrada, aunque
mantiene una ligera asimetría positiva debido a la menor cantidad de
vehículos que logran superar la barrera de las 150,000 millas en el
mercado secundario

\subsection {Distribucion de millajes por marca}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-9-1} \end{center}

En el grafico de caja y bigote se observa que las cajas son mucho mas
alargadas que las de precio, en todas las marcas menos en Tesla. Esto
quiere decir que existe una alta heterogeneidad en la muestra; coexisten
unidades ``casi nuevas'' con muy pocas millas y vehículos de alto uso
que superan las 150,000 millas. \newline \newline Los ``bigotes''
superiores de marcas como Ford, Honda y Toyota se extienden casi hasta
las 200,000 millas mientras que la marca Tesla presenta la caja más baja
y compacta de todo el gráfico. Su mediana se sitúa por debajo de las
30,000 millas , lo que confirma que es la flota con menor desgaste
físico, coherente con su naturaleza de vehículos eléctricos de reciente
comercialización. \newline \newline El gráfico evidencia que el millaje
no es uniforme entre fabricantes. Mientras que Tesla representa el
segmento de bajo uso y alta tecnología , marcas de consumo como Ford y
Toyota dominan el segmento de vehículos con alto recorrido.

\subsection {Millaje promedio por y marca por año}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-10-1} \end{center}

Se observa una relación inversa casi perfecta entre el año de
fabricación y el millaje acumulado. A medida que los vehículos son más
recientes, el millaje promedio cae drásticamente \newline \newline A
diferencia del gráfico de precios, donde las marcas estaban mas
dispersas dependiendo del grupo al que pertencen, en el gráfico de
millaje todas las marcas (incluyendo las de lujo como Mercedes y Tesla)
siguen una trayectoria muy similar y agrupada. Esto indica que el uso
promedio de un vehículo es un factor conductual del propietario que es
independiente del prestigio de la marca

\section {Correlacion entre Precio y Millaje}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-11-1} \end{center}

\begin{verbatim}
## [1] "El coeficiente de correlación es: -0.6254"
\end{verbatim}

El coeficiente de correlación de -0.6254 confirma una correlación
negativa. Visualmente, esto se observa en los datos que descienden de
izquierda a derecha: a medida que el millaje aumenta (eje X), el precio
tiende a disminuir (eje Y). Según la escala de Pearson, un valor de
\(0.62\) se clasifica como una correlación moderada-fuerte. Esto indica
que el millaje es un predictor sólido del precio, aunque no es el único
factor (existen otras variables como la marca o el tipo de combustible
que explican el resto de la varianza). \newline \newline Se observa que
la mayor concentración de datos se observa en el cuadrante inferior
izquierdo (vehículos con millaje entre 50,000 y 125,000 y precios por
debajo de los \(25,000\)). De igual forma, se observan puntos aislados
con muy poco millaje y precios muy altos (superiores a \(75,000\)).
Estos corresponden a los modelos de lujo y eléctricos (como Tesla)
analizados en las secciones anteriores. \newline \newline Por ultimo se
puede ver que la relación no parece es perfectamente lineal, sino que
muestra una ligera curvatura. El precio cae muy rápido durante las
primeras 50,000 millas y luego la caída se vuelve más gradual, lo que
sugiere un fenómeno de depreciación acelerada en los primeros años de
vida del vehículo.

\section {Estudio de precio por tipo de combustible}

\subsection {Conteo de carros por tipo de combustible por marca}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-12-1} \end{center}

Se observa que la mayoria de los carros presentes en la muestra son de
gasolina para todas las marcas menos Tesla que vende exclusivamente
carros electricos. Se observa tambien que son las marcas japonesas las
que mas carros hibridos tienen presentes en esta muestra,
particularmente Toyota, con el modelo Prius, que vendre desde el año
2000. \newline \newline Tambien se puede ver que las marcas europeas
tienen mayor cantidad de carros diesel. Mientras que Ford, marca
americana esta compuesta casi exlusivamente por carros de gasolina.

\subsection {Conteo de carros por tipo de combustible por año}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-13-1} \end{center}

Se observa en este grafico que entre el año 2000 y 2015 el tipo de
combustible mas comun es la gasolina, con los carros diesel
representando una pequeña porcion y los carros hibridos una menor aun.
Hasta ese momento los carros hibridos estan representados casi
exclusivamente por el Toyota Prius. Pero a partir del 2015 irrumpen los
carros electricos y empiezan a ganar terreno junto con los hibridos y
disminuyendo los de gasolina. Esto tiene sentido, ya que es a partir de
ese punto que entra en el mercado la marca Tesla, la cual como ya se
dijo anteriormente, vende solo carros electricos y representa la mayor
parte de este tipo de carros en la muestra. Factores como las
legislaciones europeas y estadounidenses que presionan a los fabricantes
para que diseñen carros con menor emision de CO2 afectan tambien.

\subsection {Resumen Estadistico de Precio por Tipo de Combustible}

\begin{table}[!h]
\centering
\caption{\label{tab:unnamed-chunk-14}Análisis de Precios por Combustible (Modelos 2015 - 2023)}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lccc>{}c}
\toprule
\textcolor{black}{\textbf{Tipo de combustible}} & \textcolor{black}{\textbf{Cantidad de carros}} & \textcolor{black}{\textbf{Precio promedio}} & \textcolor{black}{\textbf{Desviacion estandar}} & \textcolor{black}{\textbf{Coeficiente de Variacion}}\\
\midrule
\cellcolor{gray!10}{Diesel} & \cellcolor{gray!10}{162} & \cellcolor{gray!10}{30,712.56} & \cellcolor{gray!10}{13,738.84} & \em{\cellcolor{gray!10}{44.73}}\\
Electrico & 92 & 49,496.39 & 16,606.89 & \em{33.55}\\
\cellcolor{gray!10}{Gasolina} & \cellcolor{gray!10}{437} & \cellcolor{gray!10}{26,759.90} & \cellcolor{gray!10}{13,356.35} & \em{\cellcolor{gray!10}{49.91}}\\
Hibrido & 141 & 29,083.71 & 14,128.79 & \em{48.58}\\
\cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{Total}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{832}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{30,437.48}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{15,545.12}}} & \em{\cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{51.07}}}}\\
\bottomrule
\end{tabular}}
\end{table}

Visto lo anterior, para el analisis de precios segun tipo de
combustible, se filtraron los datos para contener solo los vehiculos de
2015 en adelante, dado que es a partir de este punto que podemos hacer
una comparacion entre los 4 tipos de combustibles. \newline \newline
Primero que nada, se comnfirma que los carros de gasolina representan la
mayor porcion de los registros segun tipo de combustible y los
electricos son la minoria; mientras que hay cierta paridad entre la
cantidad de hibridos y carros diesel. \newline \newline En cuanto al
precio se observa que los precios promedios de los carros Diesel,
Gasolina e Hibridos son similares al igual que sus desviaciones y sus
coefecientes de variacion. Por lo cual podriamos pensar que estos no son
factores que afecten el valor del carro. Sin embargo, a diferencia de
estos tres, los carros electricos tienen un valor promedio
considerablemente mas alto y una menor variabilidad. Esto puede deberse
a que la marca Tesla representa practicamente la totalidad de carros
electricos, y al ser una marca de lujo, sus precios seran mas altos.
\newline \newline Tambien puede interpretarse como que los carros
electricos, al ser una tecnologia mas nueva todavia es mas cara que
tecnologias mas antiguas y desarrolladas como los motores de combustion.

\subsection {Distribucion de Precios segun tipo de combustible}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-15-1} \end{center}

Se observa que los vehiculos electricos presentan la mediana más alta.
Esto confirma que, en promedio, son los vehículos más costosos de la
base de datos. Mientras que Híbridos, Gasolina y Diésel tienen medianas
muy similares entre sí, situándose significativamente por debajo de los
eléctricos. Esto sugiere que el mercado de combustión interna y los
híbridos compiten en rangos de precios parecidos. \newline \newline Por
otro lado, las cajas de los vehículos de Gasolina y Diésel son más
largas que la de los Eléctricos. Esto indica que hay una mayor variedad
de precios (desde modelos económicos hasta modelos de gama media-alta)
en los motores tradicionales. \newline \newline En cambio la caja de los
Eléctricos es relativamente compacta en comparación con su altura total,
lo que sugiere que sus precios, aunque altos, están más concentrados en
un rango específico de lujo o tecnología reciente.

\section {Estudio de Precio por Tipo de Transmision}

\subsection {Resumen Estadistico de Precios por Tipo de Transmision}
\begin{table}[!h]
\centering
\caption{\label{tab:unnamed-chunk-16}Análisis de Precios por Tipo de Transmision}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{lccc>{}c}
\toprule
\textcolor{black}{\textbf{Tipo de transmisión}} & \textcolor{black}{\textbf{Cantidad de carros}} & \textcolor{black}{\textbf{Precio medio}} & \textcolor{black}{\textbf{Desviación estándar}} & \textcolor{black}{\textbf{Coeficiente de Variación}}\\
\midrule
\cellcolor{gray!10}{Automatico} & \cellcolor{gray!10}{1,080} & \cellcolor{gray!10}{21,238.44} & \cellcolor{gray!10}{16,118.83} & \em{\cellcolor{gray!10}{75.89}}\\
Manual & 786 & 16,462.03 & 12,748.63 & \em{77.44}\\
\cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{Total Muestra}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{1,866}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{19,226.51}}} & \cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{14,976.39}}} & \em{\cellcolor{lightgray}{\textbf{\cellcolor{gray!10}{77.89}}}}\\
\bottomrule
\end{tabular}}
\end{table}

Se observa que los carros automaticos representan una mayor porcion de
la muestra y que tienen un precio promedio considerablemente mayor a los
manuales. Esto puede deberse a varios factores. Principalmente que la
tecnologia usada para una transmision manual es mas economica y por lo
tanto su precio de venta puede ser menor. Tambien factores como la
preferencia del consumidor, hacen que carros automaticos puedan tener
mayor demanda y por lo tanto ser vendidos a mayor precio. Por ultimo, un
factor que no se puede obviar es que los modelos mas caros de la muestra
(segmento de lujo) suelen tener tipo de transmision automatica. Como por
ejemplo los carros de la marca Tesla. \newline \newline Por ultimo,
aunque ambos tipos de transmision tienen coeficientes de dispercion
elevados, la transmisión Manual es más ``predecible'' o compacta, con un
CV del 52.41\%, sugiriendo que estos vehículos se mantienen en un rango
de precio más estandarizado. Mientras que en los carros automaticos, se
encuentran tanto carros de lujo como modelos mas economicos.

\subsection {Distribucion de Precios por Tipo de Transmision}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-17-1} \end{center}

Lo descrito anteriormente se puede confirmar en los graficos de caja de
bigote. Cabe destarcar que ambos grupos presentan una gran cantidad de
outliers por encima del bigote superior.

\section {Correlaciones entre variables numericas}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-18-1} \end{center}

Entre las correlaciones, interesa encontrar cuales son las variables
cuantitativas que afectan el precio de los carros:

\begin{itemize}

\item El tamano del motor no es un factor que afecte el precio del carro, ya que aunque los motores mas grandes se suelen asociar a mayores precios en los años recientes los motores han tendido a disminuir de tamano, incluso en camionetas o SUV, gracias a la adicion de turbos o sistemas hibridos que compensan la perdida de cilindrada.

\item El año de fabricacion afecta directamente el precio del carro, esto significa que mientras mas recientemente haya sido fabricado un carro, mayor sera su precio de venta. Un coeficiente de relacion de 0.73 se puede interpretar como una correlacion fuerte.

\item Por otro lado, el millaje afecta inversamente al precio. Es decir, mientras mas millas se han recorrido en un carro, menor sera su precio de venta. Un coeficiente de correlacion de 0.63 se intrepreta como una correlacion moderada a fuerte.
\end{itemize}

\chapter{Conclusiones y Recomendaciones}

El análisis descriptivo y exploratorio realizado sobre la muestra de
1,866 vehículos permite establecer conclusiones fundamentales sobre la
dinámica de precios en el mercado de segunda mano para el año 2023. A
continuación, se presentan los hallazgos finales y las sugerencias
estratégicas derivadas del estudio.

\section {Conclusiones}

\begin{itemize}

\item Se confirma que el año de fabricación y el millaje son los predictores más sólidos del valor de mercado. La correlación positiva fuerte ($r = 0.73$) con la antigüedad y la correlación negativa moderada-fuerte ($r = -0.63$) con el kilometraje validan la hipotesis presentada al principio del informe.

\item Se confirma que existe una brecha estructural entre marcas de consumo masivo (Ford, Honda, Toyota) y marcas de lujo (Audi, BMW, Mercedes Benz, Tesla). Factores como prestigio de la marca afectan el precio de los vehiculos. Pero luego de aproximadamente 20 años de antiguedad la brecha de precios entre marcas de lujo y de consumo masivo tiende a cerrarse.

\item A diferencia del precio, el uso del vehículo (millaje) es un factor conductual independiente del prestigio de la marca. Todas las marcas, a excepción de Tesla por su reciente inserción, muestran trayectorias de desgaste similares a lo largo del tiempo, lo que sugiere que el perfil de uso es intrínseco al propietario y no al fabricante.

\item Los vehículos automáticos predominan en la muestra y mantienen precios promedios superiores. Esto responde tanto a una mayor demanda por parte del consumidor moderno como a la estandarización de esta tecnología en los segmentos de alta gama.
\end{itemize}

\section {Recomendaciones}

\begin{itemize}

\item Optimización de Compra (Consumidor): Para maximizar la relación valor-precio, se recomienda adquirir vehículos que hayan superado la barrera de las 50,000 millas, punto en el cual la curva de depreciación acelerada inicial comienza a estabilizarse, permitiendo una caída de precio más gradual en años posteriores.

\item Estrategia de Venta (Propietarios): Dado que el año de fabricación tiene un impacto más fuerte que el millaje en la valoración ($0.73$ vs. $0.63$), es preferible renovar el activo por antigüedad antes que por kilometraje acumulado para evitar pérdidas significativas de capital.

\item  Se recomienda la inclusión de nuevas Variables para futuros estudios; como integrar el historial de mantenimiento y el estado de la batería como variables explicativas, ya que podrían explicar la varianza que el millaje y el año no cubren totalmente. Variables como tipo de carroceria tambien permitirian hacer un estudio mas completo pues permitiria segmentar el estudio y hacerlo mas preciso. De igual forma, la inclusion de los precios originales de los vehiculos ayudaria a entender la depreciacion real de los activos.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   REFERENCIAS                     %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mantenemos la estructura natbib de tu plantilla
\renewcommand{\bibname}{Lista de Referencias}
\bibliographystyle{apalike} 
\bibliography{bibliografia.bib} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   APÉNDICES                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
